server:
  port:  8888
spring:
  application:
    name: erudio-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mayke1996/microservices-config-server
          default-label: main
          search-paths:
          - 'greeting-service*'
            